version: '2.2'

services:
  os:
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        OS_VERSION: ${OS_VERSION:-2.68.1_rev1}
        DEVICE_TYPE: ${DEVICE_TYPE:-intel-nuc}
    privileged: true
    stop_signal: SIGRTMIN+3
    stop_grace_period: 30s
    volumes:
      - /lib/modules:/lib/modules:ro
      - ${CONFIG_JSON:-./config.json}:/var/local/boinc.config.json
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/lib/journal
      - /mnt/boot
      - /mnt/state
      - /mnt/data
    # this is required for the dns option to have any effect
    # see https://github.com/docker/compose/issues/2847#issuecomment-658999887
    network_mode: bridge
    dns:
      - 127.0.0.2
    tty: true
